apiVersion: v1
kind: ConfigMap
metadata:
  name: bookdelivery-db-config-map
data:
  DB_HOST_SERVICE_NAME_VALUE: bookdelivery-app-db-service
  DB_SCHEMA_VALUE: bookdelivery-app
  DB_PORT_VALUE: "3306"
