apiVersion: v1
kind: Service
metadata:
  name: bookdelivery-db-service
spec:
  type: NodePort
  selector:
    app: bookdelivery-app  
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
      nodePort: 31231
  
