apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookdelivery-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bookdelivery-app
  template:
    metadata:
      labels:
        app: bookdelivery-app
    spec:
      containers:
      - name: bookdelivery-app
        image: sankha169/bookdelivery:latest
        ports:
        - containerPort: 1221
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: bookdelivery-db-secret
              key: DB_PASSWORD_VALUE
        - name: MYSQL_DATABASE
          valueFrom:
            configMapKeyRef:
              name: bookdelivery-db-config-map
              key: DB_SCHEMA_VALUE
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: bookdelivery-db-secret
              key: DB_PASSWORD_VALUE
        - name: MYSQL_HOST
          valueFrom:
            configMapKeyRef:
              name: bookdelivery-db-config-map
              key: DB_HOST_SERVICE_NAME_VALUE
        - name: MYSQL_PORT
          valueFrom:
            configMapKeyRef:
              name: bookdelivery-db-config-map
              key: DB_PORT_VALUE
        - name: SPRING_DATASOURCE_USERNAME
          value: ${DATABASE_USERNAME}
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: bookdelivery-db-secret
              key: DB_PASSWORD_VALUE
        - name: BOOK_DELIVERY_DB_IP
          value: database
        - name: BOOK_DELIVERY_DB_PORT
          value: "3307"
        - name: SPRING_DATASOURCE_URL
          value: jdbc:mysql://172.17.0.1:3307/bookdelivery
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: bookdelivery-db-pvc
